### ISSUE TITLE
question: storing model in database?

### ISSUE THREAD

**Issue by vsoch** [martialblog/word_embedding_storage#8]
Hi @martialblog ! Have you given any thought to (or know about) efforts to store not just the vectors, but the model itself in a database? I'm just starting to explore this idea and was doing searching and came across your repo here. Thank you!

**Comment by martialblog** [comment]
Hi, I have not tried that myself. The usecase at the time was to store and retrieve vectors for one or more words.
Storing the entire model in a database is very different I'd assume. Since the models are usually blobs, you'd have to store a big chunk of data. 

I know there are some tools for serving ML model (e.g. KServing or Feast), might be possible to leverage those.

**Comment by vsoch** [comment]
Thanks, I'll take a look into those! I was looking at the doc2vec "model" and it's just a pickle, so I suspect there could be a way to serialize that (and save / load from) a database, and maybe I'll try that soon.

Thanks for your help!
